### ISSUE TITLE
Feature request: Expand button for datasets with many downloadlinks

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#114]
Four datasets have very many links .. Would be great to hide these behind a "+" in BYOD so searches give a better overview...

AMSRE
TRMM
GLDAS
FREEZE THAW
(and GRDC but that will be removed).

**Comment by p-a-s-c-a-l** [comment]
This requires proper assignment of *collection* attributes which as not been done for newly imported datasets as described here: https://github.com/switchonproject/cids-custom-switchon/issues/134

**Comment by esafa** [comment]
There is only four big ones (AMSRE 3000 links, THAW 1000, GLDAS 1300.... we
could assign these to four collections and the rest can be uncategorized.

However.. doing it manually with metadata wiz is not an option (some 5000
rows need to be changed).. Can you script it in SQL?


On Fri, Jul 10, 2015 at 12:23 PM, Pascal Dihé <notifications@github.com>
wrote:

> This requires proper assignment of *collection* attributes which as not
> been done for newly imported datasets as described here:
> switchonproject/cids-custom-switchon#134
> <https://github.com/switchonproject/cids-custom-switchon/issues/134>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/114#issuecomment-120358280>
> .
>



-- 
Esa Falkenroth
mobile: 0702-104028 (intl +46702104028)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
Yes, that can be done. But would be inconsistent to do it just for those resources.

Anyway, the feature you are requesting, while a first glance looks very easy to implement for end users, is in reality a non-trivial problem.

Example: Search finds in total 1000 resources and 850 of them are AMSRE resources. Of course, the client cannot not load the complete search result (1000 resources) at once. Thus, the search result is partitioned. The default page size (# of search results loaded from the server) is 10. Next & Prev Buttons let the user navigate through the complete search result.

Presently, you get the first 10 AMSRE resources out 1000 search results (and see 10 AMSRE resources in the list. Then you can click on next to see the next 10 AMSRE resources because search results are ordered by resource name. 

After implementing the feature (which is not so trivial to implement in the JS Client as it looks like) you would expect to see just 1 ASMR resources (representing results # 1-850) with a plus sign and below that also other resources (results 851 ... 859)?

But this would break the whole paging mechanism which relies on fixed page index and page size. E.g. consider mixing  THAW 1000 and  GLDAS 1300 resources.  GLDAS 1300 expanded by user (plus pressed),   THAW 1000 not. What happens, when the user clicks on next? What happens, when the user expands or collapsed a resource and clicks on prev? This makes navigating through the search result not only unpredictable for the user but requires also considerable changes in the current search implementation (page index is not enough, the state of the client has to be considered too).

There is a much simpler solution: Apply a Post Search Filter (like for access conditions and functions) to exclude results of a specific category from the search results.

**Comment by p-a-s-c-a-l** [comment]
Done. See https://github.com/switchonproject/cids-custom-switchon-server/issues/59
