### ISSUE TITLE
Minor issue: "Black clouds" cover Europe map for resource 11898 (beta)

### ISSUE THREAD

**Issue by esafa** [switchonproject/sip-html5#132]
Go to link http://www.water-switch-on.eu/sip-webclient/byod/#/map/object/11898
Zoom in over Central Europe.

![image](https://cloud.githubusercontent.com/assets/6159801/17407732/b3699e26-5a68-11e6-8818-447c41e528e0.png)

**Comment by esafa** [comment]
As a user, I expect to be able to read the city names on the map when zooming into one area.

**Comment by esafa** [comment]
I see what is happening. The zooming takes extremely long time.... I checked some 10 minutes later and the map looked fine again (still black area but much more hires and smaller).

**Comment by p-a-s-c-a-l** [comment]
This happens when a layer with a very high feature count (> 50.000 polygons) is loaded for the first time, e.g. corine landcover layers. Map tiles are generated and cached on request, this can take some time.

Now I'm pre-seeding the layer up to zoom level 10 (~ 280.000 tiles in cache). Now the problem should be gone.

![gwc-seed](https://cloud.githubusercontent.com/assets/1788226/17431499/a1f3f4a6-5afa-11e6-946e-6238be049495.png)

**Comment by esafa** [comment]
Great!

Den 5 aug. 2016 10:55 AM skrev "Pascal Dihé" <notifications@github.com>:

**Comment by p-a-s-c-a-l** [comment]
done
