### ISSUE TITLE
User story no. 2 

### ISSUE THREAD

**Issue by rcnijzink** [switchonproject/sip-html5#25]
As a hydrologist, i need to find all available data (Emma’s data) for my catchment(s) at once, so i can build my catchment experiment database.

**Comment by duropa** [comment]
does it mean a search for given basin boundary (shape file) or just a name in the keywords?

**Comment by rcnijzink** [comment]
Generally more something like a box with coordinates, that could cover a basin, but also a wider area (so data close to the basin can be found as well)

**Comment by duropa** [comment]
ok. then i would not called it my catchment, but in given bounding box...
is it possible to extend the story to "...find and sort all..."?

**Comment by schlob** [comment]
There are a number of ways how this can be supported
Simple BB or point as search geometry
A Polygon as search geometry
A Polygon selected from a data source e.g. shape of WFS as search geometry
A freely drawn Polygon e.g. if you have a rastermap of the catchments but no access to the poygon
you could simply draw along the lines of the map

**Comment by schlob** [comment]
Probably it makes sense to introduce some search options as well
--> use buffer, no intersction (show only results that are completely in the area), intersection etc.
But let's start with the BB thing :-)

**Comment by p-a-s-c-a-l** [comment]
**Mockups for user story no. 2**

Define catchment are (e.g. bounding box) to search for resource data:

![uc020-010-geospatial-search-bbox](https://cloud.githubusercontent.com/assets/1788226/5975581/cbc57ba0-a882-11e4-82e0-2282f6af862e.png)

Define additional options to control the geospatial search (e.g. define a buffer to find also nearby basins):

![uc020-020-geospatial-search-options](https://cloud.githubusercontent.com/assets/1788226/5975584/cf91b438-a882-11e4-8d56-0acb91532e78.png)

**Comment by schlob** [comment]
what does "so i can build my catchment experiment database" mean exactly?
Do you want to download all results with one interaction?

Probably finding everthing you need will be a multi step process - for this whe have the idea
to use something similar to an amazon shopping basket.

**Comment by esafa** [comment]
@duropa : what do you mean by "find and sort all"?  Do you want all data
sets sorted by distance to some catchment? Or what kind of sorting are you
looking for?


On Fri, Jan 30, 2015 at 1:30 PM, Sascha Schlobinski <
notifications@github.com> wrote:

> what does "so i can build my catchment experiment database" mean exactly?
> Do you want to download all results with one interaction?
>
> Probably finding everthing you need will be a multi step process - for
> this whe have the idea
> to use something similar to an amazon shopping basket.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72194225>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by esafa** [comment]
also... how would you like to define the area? by selecting an area on a
map (NW-corner/SE-corner)? Or do you prefer entering it with lat/long
coordinates as numbers? @duropa mention shape files?



On Fri, Jan 30, 2015 at 8:37 PM, Dr Falkenroth <nospam@falkenroth.se> wrote:

> @duropa : what do you mean by "find and sort all"?  Do you want all data
> sets sorted by distance to some catchment? Or what kind of sorting are you
> looking for?
>
>
> On Fri, Jan 30, 2015 at 1:30 PM, Sascha Schlobinski <
> notifications@github.com> wrote:
>
>> what does "so i can build my catchment experiment database" mean exactly?
>> Do you want to download all results with one interaction?
>>
>> Probably finding everthing you need will be a multi step process - for
>> this whe have the idea
>> to use something similar to an amazon shopping basket.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72194225>
>> .
>>
>
>
>
> --
> Esa Falkenroth
> mobile: 070-666-14-14 (intl +46706661414)
> work: 011-4958298 (intl +46114958298)
> skype: Esa.Falkenroth
> email: nospam@falkenroth.se (for business mail)
> email: esa@falkenroth.se (for private mail)
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by duropa** [comment]
dear esa
i mean to have an option to sort results e.g. 
according to date of acquisition, keyword, or 
some field available in the metadata....
d.
At 20:37 30.1.2015, you wrote:
>@duropa : what do you mean by "find and sort all"? Do you want all data
>sets sorted by distance to some catchment? Or what kind of sorting are you
>looking for?
>
>
>On Fri, Jan 30, 2015 at 1:30 PM, Sascha Schlobinski <
>notifications@github.com> wrote:
>
> > what does "so i can build my catchment experiment database" mean exactly?
> > Do you want to download all results with one interaction?
> >
> > Probably finding everthing you need will be a multi step process - for
> > this whe have the idea
> > to use something similar to an amazon shopping basket.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72194225>
> > .
> >
>
>
>
>--
>Esa Falkenroth
>mobile: 070-666-14-14 (intl +46706661414)
>work: 011-4958298 (intl +46114958298)
>skype: Esa.Falkenroth
>email: nospam@falkenroth.se (for business mail)
>email: esa@falkenroth.se (for private mail)
>
>­
>Reply to this email directly or 
><https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72257648>view 
>it on GitHub.

*******************************************************************************
Assoc. Prof. Juraj Parajka
Institute of Hydraulic Engineering and Water Resources Management
Vienna University of Technology
Karlsplatz 13/222, A-1040 Vienna, Austria
www.hydro.tuwien.ac.at
*******************************

**Comment by esafa** [comment]
Ok, This is additional functionality and it is indeed a good candidate for
a new user story. Perhaps userstory number four?

If many data sets match the keywords you are searching for it could indeed
be good to have them sorted in various ways.  Especially sort of datasets
by keyword is a bit tricky since one dataset may be associated with several
keywords (even from different keywordlists).

@p-a-s-c-a-l : Could we throw in a sort by "date of acquisition" without
prolonging implementation?



On Sat, Jan 31, 2015 at 5:57 PM, duropa <notifications@github.com> wrote:

> dear esa
> i mean to have an option to sort results e.g.
> according to date of acquisition, keyword, or
> some field available in the metadata....
> d.
> At 20:37 30.1.2015, you wrote:
> >@duropa : what do you mean by "find and sort all"? Do you want all data
> >sets sorted by distance to some catchment? Or what kind of sorting are
> you
> >looking for?
> >
> >
> >On Fri, Jan 30, 2015 at 1:30 PM, Sascha Schlobinski <
> >notifications@github.com> wrote:
> >
> > > what does "so i can build my catchment experiment database" mean
> exactly?
> > > Do you want to download all results with one interaction?
> > >
> > > Probably finding everthing you need will be a multi step process - for
> > > this whe have the idea
> > > to use something similar to an amazon shopping basket.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <
> https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72194225>
>
> > > .
> > >
> >
> >
> >
> >--
> >Esa Falkenroth
> >mobile: 070-666-14-14 (intl +46706661414)
> >work: 011-4958298 (intl +46114958298)
> >skype: Esa.Falkenroth
> >email: nospam@falkenroth.se (for business mail)
> >email: esa@falkenroth.se (for private mail)
> >
> >­
> >Reply to this email directly or
> ><
> https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72257648>view
>
> >it on GitHub.
>
> *******************************************************************************
>
> Assoc. Prof. Juraj Parajka
> Institute of Hydraulic Engineering and Water Resources Management
> Vienna University of Technology
> Karlsplatz 13/222, A-1040 Vienna, Austria
> www.hydro.tuwien.ac.at
> *******************************
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72325807>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
> @p-a-s-c-a-l : Could we throw in a sort by "date of acquisition" without prolonging implementation?

Sure, sorting is no big issue. This would be a new a new user story, though.
I'd like to close the other user stories first. What about user [story no. 1](https://github.com/switchonproject/sip-html5/issues/13)? Can we consider it fulfilled?

**Comment by esafa** [comment]
Ok. good. Sorting is new userstory. Ill put it up as candidate for fourth
userstory.

Regarding story #1... Keep it open until the group says "yey, this works.
Thanks.. it is so easy to use for hydrologists, and it does what we asked
for in the user story" :)
Ill try to get some response from them.


On Mon, Feb 2, 2015 at 9:53 AM, Pascal Dihé <notifications@github.com>
wrote:

> @p-a-s-c-a-l <https://github.com/p-a-s-c-a-l> : Could we throw in a sort
> by "date of acquisition" without prolonging implementation?
>
> Sure, sorting is no big issue. This would be a new a new user story,
> though.
> I'd like to close the other user stories first. What about user story no.
> 1 <https://github.com/switchonproject/sip-html5/issues/13>? Can we
> consider it fulfilled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72423440>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by p-a-s-c-a-l** [comment]
This video shows the current implementation of user story no. 2:

[![us-2-yt](https://cloud.githubusercontent.com/assets/1788226/6025043/c805c9ca-abcf-11e4-84e0-9baefbd706bf.png)](https://www.youtube.com/watch?v=5N6iX05mO_A&feature=youtu.be)

- Navigate to some drainage basins. As **one example** we show some basis of Austria obtained from [gis.lebensministerium.at](http://gis.lebensministerium.at/wmsgw/gs103601/?&service=wms&version=1.1.1&request=GetCapabilities).
- draw a *search polygon* that covers the basins of interest
- execute the search for data inside the basins
- **no results are found due to insufficient data registered in Meta-Data Repository ("Emma*s datasets").** There is no data available at this spatial resolution. Smallest datasets cover Europe. Although we could perform a search for data sets that **intersect** with the selected basins geometries, this would return **all** resources in the  Meta-Data Repository - not very useful.
- So find some resources, we have to extend the search area to Europe
- Zoom out, draw a large bounding box and start the search
- Resources are found. Their spatial extent is shown in the map
- Resources can be shown in the list. Sorting is also possible.

**Comment by p-a-s-c-a-l** [comment]
This video shows another possibility to search for data related to "catchments" or any other geographic feature.

[![us-2-impl2](https://cloud.githubusercontent.com/assets/1788226/6041613/39531d5e-ac7e-11e4-96af-06bf4565431e.png)](https://www.youtube.com/watch?v=8u3kcYmg-A4&feature=youtu.be)

- restrict results to resources that are tagged with CUSAHI Keyword "water"
- set a limit to restrict the search results to 20 resources. (see https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72692031 for an explanation why this is required)
- set an option to include also resources that **intersect** with the search geometry
- navigate to basins of interest and draw a bounding box to define the search geometry
- start search.
- only the first 20 resources matching the query are returned. Note: Data covers whole Europe and is probably not what you have expected.

For a description of the limitations of data sets currently available in the Meta-Data Repository and how the situation could be improved, please refer to https://github.com/switchonproject/cids-custom-switchon/issues/61 and https://github.com/switchonproject/cids-custom-switchon/issues/110 

@rcnijzink, @duropa regarding the implementation, please let me know if this is what you've expected.

**Comment by rcapell** [comment]
Thanks for the preview videos. This is more than i had expected from the user story. From my perspective, a simple search box where the user can enter corner coordinates would have sufficed. Anyway, the interactive map works as well as far as I can see, and it looks fancier and searches are probably faster.
Comments/questions from my side:
1.  Where does the Austria map overlay come from, is that something a user could put there?
2. the intersect/encloses options are useful
3. I can see an issue with this spatial search, depending on how data sets are represented in the sip. Think of the Global Runoff Data Centre (GRDC) data, their data set spans the earth, but not every point on earth has a GRDC station in it. For a spatial search on GRDC data to be meaningful, the sip must know the GRDC station locations, otherwise there will always be a match. The GRDC publishes kml layers of station locations, but I don't know if the sip will provide a way to incorporate that information. And then the next data publisher might choose another way to provide access to measurement locations. Maybe the sip should provide an interface according to some standard to exchange metadata with data providers (given that they support the standard)? Is there such a standard?

**Comment by schlob** [comment]
regarding 3.
yes - the spatial information on the datasets is quite useless atm. As you have indicated meta data needs to be collected on a lower level (and then the corresponding data made accessible) to be useful.
This is not a "standard format" issue but rather an issue about the users definining a "good" (added value) level for the actual meta data to be collected. There can be no general solution as this is solely content depenent. However, there can be something like best practices. 
So let's define what is useful meta data in the project context. As we can see simply taking a standard and putting some meta data in is not the end of the tunnel if not completely useless:-)

**Comment by esafa** [comment]
Good comments.. As Sascha says the currentspatial information Emmas found
is quite useless since it gives the bounding box of entire datasets rather
than individual observation sites. I will add a userstory candidate to the
inspiration document "As hydrologist, I want to do spatial search
individual station locations (rather than the bounding box of all stations
contain in a huge dataset such as GRDC), SO I can find observation data for
my experiments  (as @rcapell pointed out: "the sip must know the GRDC
station locations, otherwise there will always be a match.").

 Note: for gridded data the bbox in Emmas metadata is more useful.


On Wed, Feb 4, 2015 at 4:37 PM, Sascha Schlobinski <notifications@github.com
> wrote:

> regarding 3.
> yes - the spatial information on the datasets is quite useless atm. As you
> have indicated meta data needs to be collected on a lower level (and then
> the corresponding data made accessible) to be useful.
> This is not a "standard format" issue but rather an issue about the users
> definining a "good" (added value) level for the actual meta data to be
> collected. There can be no general solution as this is solely content
> depenent. However, there can be something like best practices.
> So let's define what is useful meta data in the project context. As we can
> see simply taking a standard and putting some meta data in is not the end
> of the tunnel if not completely useless:-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72876415>
> .
>



-- 
Esa Falkenroth
mobile: 070-666-14-14 (intl +46706661414)
work: 011-4958298 (intl +46114958298)
skype: Esa.Falkenroth
email: nospam@falkenroth.se (for business mail)
email: esa@falkenroth.se (for private mail)

**Comment by duropa** [comment]
just to add to grdc dataset...in our next experiment we plan to develop a catalogou of flood characteristics for each station (or almost each) of the grdc dataset...so we can help with some metatdata if needed...

 
cheers

d.


 
-----Original message-----

**Comment by esafa** [comment]
Today, I got confirmation that we will have one (or possibly even two)
summerworkers for improvements on metadata etc.
Den 4 feb 2015 19:18 skrev "duropa" <notifications@github.com>:

**Comment by rcnijzink** [comment]
This looks very good! The box and polygons and intersect options are more than I expected, but it is very useful. I do also agree with the comments of Rene and Duro about finding for example stations of the grdc. This was also what I had in mind when we defined this user story, maybe also because, as far as I know, there doesn't really exist a good search platform that searches on this level. The sip would really adds something here if that would be possible, but indeed, it maybe hard to realize as it is a lower level of (meta-) data.

**Comment by duropa** [comment]
this is very nice...i'm looking foward to an online test version...
d.

At 15:12 4.2.2015, you wrote:

>This video shows another possibility to search 
>for data related to "catchments" or any other geographic feature.
>
><https://www.youtube.com/watch?v=8u3kcYmg-A4&feature=youtu.be>
>us-2-impl2
>    * restrict results to resources that are 
> tagged with CUSAHI Keyword "water"
>    * set a limit to restrict the search results 
> to 20 resources. (see 
> <https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72692031>#25 
> (comment) for an explanation why this is required)
>    * set an option to include also resources 
> that intersect with the search geometry
>    * navigate to basins of interest and draw a 
> bounding box to define the search geometry
>    * start search.
>    * only the first 20 resources matching the 
> query are returned. Note: Data covers whole 
> Europe and is probably not what you have expected.
>
>For a description of the limitations of data 
>sets currently available in the Meta-Data 
>Repository and how the situation could be 
>improved, please refer to 
><https://github.com/switchonproject/cids-custom-switchon/issues/61>switchonproject/cids-custom-switchon#61 
>and 
><https://github.com/switchonproject/cids-custom-switchon/issues/110>switchonproject/cids-custom-switchon#110 
>
>
><https://github.com/rcnijzink>@rcnijzink, 
><https://github.com/duropa>@duropa regarding the 
>implementation, please let me know if this is what you've expected.
>
>­
>Reply to this email directly or 
><https://github.com/switchonproject/sip-html5/issues/25#issuecomment-72860156>view 
>it on GitHub.

*******************************************************************************
Assoc. Prof. Juraj Parajka
Institute of Hydraulic Engineering and Water Resources Management
Vienna University of Technology
Karlsplatz 13/222, A-1040 Vienna, Austria
www.hydro.tuwien.ac.at
*******************************

**Comment by p-a-s-c-a-l** [comment]
Thank you for your comments and suggestions. I'll considering them in the discussion on new User Stories on Google Drive: https://docs.google.com/spreadsheets/d/1o8__O1ZcgN9k_prbcBvEBSiTVTGvAb9VN8r9dsxevEE/edit#gid=0

**Comment by p-a-s-c-a-l** [comment]
Closed.
